### ISSUE TITLE
Idea: Create an installer

### ISSUE THREAD

**Issue by jdmclark** [jdmclark/jkgfxmod#21]
Currently, JkGfxMod must be installed manually. It would be a lot nicer if you could run an install program, select your version of JK/MotS from a list, click OK, and then it all just works.

For the original CD-ROM versions I don't think manual installation is a big deal, but the process is more difficult for the digital versions (currently: patching the executable back to 1.0, renaming files, etc.). Much of this difficulty is due to #11, which suggests the Steam JediKnight.exe may have a subtly broken binary patch applied to it - a patch that must be removed to use JkGfxMod. Given the popularity of Steam, #11 means the most difficult installation path is probably also the most common one.

**Comment by SirYodaJedi** [comment]
The biggest issue I see with implementing this is that MotS still needs a No-CD patch according to `./doc/install.md`, which is a grey area that I don't think fits with the mod's current license. While it is really easy to find pirated copies of the retail discs (which can just be mounted as .iso images, as the game only uses a simple disc check), requiring such is a sub-optimal solution.

At least it is a lot easier to bypass the retail version's disc check in DFII, as that just requires copying a file that was present on the original cd to a folder under the installed game.

**Comment by GeneralTantor** [comment]
Got one made guys it includes some of the texture packs but works great check it out: https://www.moddb.com/mods/jedi-knight-remastered
It be easy enough to make without the packs included. Note I used the old version of the mod since for some reason the latest version gets flagged as a virus... Darn windows defender.... But still works great though! Can't wait till the next version keep up the good work!
