### ISSUE TITLE
Anti-Aliasing

### ISSUE THREAD

**Issue by PhiMue86** [jdmclark/jkgfxmod#25]
Is it possible? Or will it be added?

Great work, btw.

**Comment by SirYodaJedi** [comment]
It actually had MSAA until [v0.0.7](https://github.com/jdmclark/jkgfxmod/releases/tag/v0.0.7). I can't find the particular commit, so I'm not 100% sure, but this is probably due to changes in how the injector renders effects. It is possible that it was causing specular aliasing due to being partly deferred, only @jdmclark knows for sure.

Some sort of post-process AA, such as SMAA, would probably be easy enough to add, but I'd really like to see an option for FSAA or resolution scaling, as these would be much more accurate. It might be possible with `internal_resolution` — I haven't tried — but using a percentage of the screen resolution, like [gzdoom](https://github.com/coelckers/gzdoom), would be more intuitive anyway.

**Comment by jdmclark** [comment]
> It actually had MSAA until [v0.0.7](https://github.com/jdmclark/jkgfxmod/releases/tag/v0.0.7). I can't find the particular commit, so I'm not 100% sure, but this is probably due to changes in how the injector renders effects. It is possible that it was causing specular aliasing due to being partly deferred, only @jdmclark knows for sure.

The main reason I removed MSAA is because it was inconvenient to work with at the time. That said, I also wasn't happy with the tradeoffs in this case. Primitive interiors in JkGfxMod are always either trivial or contain high-frequency details/artifacts (or both, if you're running with nearest neighbor texture sampling). I'm not sure MSAA makes as much sense here as it does in e.g. a modern physically based forward renderer.

> Some sort of post-process AA, such as SMAA, would probably be easy enough to add, but I'd really like to see an option for FSAA or resolution scaling, as these would be much more accurate. It might be possible with `internal_resolution` — I haven't tried — but using a percentage of the screen resolution, like [gzdoom](https://github.com/coelckers/gzdoom), would be more intuitive anyway.

This is my preference too. I'm currently leaning toward SMAA for slower machines, and some kind of configurable supersampling (box filter or a proper Halton sequence sample pattern).

**Comment by jdmclark** [comment]
As noted in the above commits, I've re-added MSAA and implemented SSAA on top of it (using GL_ARB_sample_shading). I've also created a separate issue to track discussion about postprocess AA.

I think this is probably sufficient for now, so I'm closing this issue as fixed.

**Comment by PhiMue86** [comment]
Great! Are you going to upload a new release version?
