### ISSUE TITLE
Add advice to start a new game to installation guide

### ISSUE THREAD

**Issue by KolyaKorruptis** [jdmclark/jkgfxmod#40]
Might just be me, but it took me way too long to figure out why I got crashes, mixed up textures, etc. All the time I had been loading a save at the start of level 1.

In any case it wouldn't hurt to add this advice to the instructions.

**Comment by jdmclark** [comment]
Hi @KolyaKorruptis 

Thanks for the suggestion. This is a flaw in how JK itself handles game mods and savefiles, so I'm not sure the most appropriate way or place to document this advice.

From our side: It's always safe to reuse savefiles after switching to/from JkGfxMod or changing material packs. For example, anybody who's just switching from dgVoodoo2, or only interested in using the Neural Upscale texture pack, shouldn't be given this advice. Their existing savefiles will work perfectly.

However, it's almost never safe to reuse savefiles after installing any JK game mod. This can lead to confusing situations like FastGamerr's JKGFX2019, which bundles a game mod with a material pack for extra effects. JkGfxMod is present, but the real problem is the game mod, not the material pack. You'd have the same problem after installing any other mod, whether or not you were using JkGfxMod.

I'll need to give some thought to how this can be documented without causing more confusion. My first instinct is that this should be communicated by the original mod authors. Have you reached out to them?

**Comment by KolyaKorruptis** [comment]
You're right, it isn't jkgfxmod, but game-mods that require starting a new game. 
I haven't reached out to those mod authors yet. This certainly would be useful for future mod releases. Although establishing a consistent style of documentation will be difficult.
jkgfxmod provides a single chokepoint where users will pass through and could see such a  warning, but I understand that explaining mod usage isn't actually your territory.
