### ISSUE TITLE
hud_scale leads to minimap problems

### ISSUE THREAD

**Issue by ZellSF** [jdmclark/jkgfxmod#43]
hud_scale 8.0 vs hud_scale 1.0 here:
https://www.youtube.com/watch?v=upJ2Vhg7kXY
(this is the first level, the first elevator you find). Seems to draw some duplicate part of the minimap upscaled.

**Comment by jdmclark** [comment]
Hi @ZellSF 

Thanks for reporting. This is a known issue due to how JkGfxMod HUD scaling works.

Jedi Knight natively draws all of the overlay elements to the front buffer in software. JkGfxMod 'tricks' JK into drawing to a texture, instead, and applies the texture to a HUD mesh (with different parts scaled up depending on your settings). Unfortunately, this means the minimap also gets blown up anywhere it overlaps another overlay element (like the console messages or the active item indicator) and there is no good way for JkGfxMod to isolate the minimap texture from the rest.

I'm not sure how this can be fixed, but I'm going to leave this bug open for future reference.

**Comment by bangstk** [comment]
I'd think the most elegant way to solve this would be to find a way to crop the map drawing function to sections that other HUD areas are not overlapping (perhaps a fixed number of pixels away from the edges of the screen rather than the whole screen) but that's getting into .exe modifications at that point

**Comment by jdmclark** [comment]
Based on the following:
- Jedi Knight natively draws all HUD elements into a single texture, including the minimap.
- There is nothing JkGfxMod can do to get a clean copy of the HUD without the map.
- Fixing this would require a binary patch, which is outside the scope of JkGfxMod.
- The way JK draws its HUD is extremely inefficient. If source level modification of JK ever does become possible, the original HUD code should be replaced in its entirety, making this fix moot.

I am closing this bug wontfix.
