### ISSUE TITLE
Is WideScreen or UltraWide Native (Fov)  ?

### ISSUE THREAD

**Issue by TP555** [jdmclark/jkgfxmod#5]
Hi

i have the GOG Version , when im Test with the Original Gog .exe File , i have a very big oversized Screen with 2560x1080

To fix this im use this ::

http://jkdf2.net/index.php?page=ProjectDisplay&pid=96
im use Mip Map Fov 120 , to Force correct UltraWide Aspect Ratio   !

**Comment by jdmclark** [comment]
Hi @TP555 

Thanks for your report. Unfortunately JkGfxMod is not able to change how JK transforms the original geometry, so the FOV is always whatever JK uses internally. The best way to work around this problem is probably with a third party binary patch (like you're using). I am unfortunately not familiar enough with offerings to recommend or officially support any of them.

Closing since this issue is outside the scope of jkgfxmod.
