### ISSUE TITLE
Inject flagging as Virus

### ISSUE THREAD

**Issue by GeneralTantor** [jdmclark/jkgfxmod#51]
Hello,
Not sure why but the latest version of the mod Windows defender is flagging it as a virus?
I added an exception but why would it be doing that?
Thanks,
General Tantor

**Comment by jdmclark** [comment]
Hi @GeneralTantor 

Modern antivirus programs use signature-based detection engines that are increasingly prone to false positives as the population of malware grows over time. This is a major annoyance for all open source software developers. The odds of any program being detected as a virus are effectively random. Software that's extremely popular or made by large companies gets manually whitelisted by antivirus companies, but for everybody else it's a free for all.

JkGfxMod is built on GitHub's (Microsoft's) build servers using only the code in this repository. You can audit this yourself here: https://github.com/jdmclark/jkgfxmod/actions/runs/63797777

If you're still concerned, you can also build the code yourself using the community edition of Visual Studio 2019.

Unfortunately there's not much more information or help I can offer on this, and there's nothing I can do to get JkGfxMod whitelisted. Closing as invalid since this is a Windows Defender design flaw, not a JkGfxMod issue.

Thanks.

**Comment by GeneralTantor** [comment]
Okay I can whitelist it on my own but it seems to just reflag again ill just use the older version for now and download the next version when its done.
